name: CI

on:
  push:
    branches:
      - transpire
    tags:
      - v*

jobs:
  transpire-ci:
    uses: ocf/transpire-ci/.github/workflows/trigger.yml@master
    with:
      module_name: notes
    secrets:
      TRANSPIRE_CI_PAT: ${{ secrets.TRANSPIRE_CI_PAT }}
